### ISSUE TITLE
Add user registration

### ISSUE THREAD

**Issue by kkadusic** [ahajradino1/payment-dashboard-webapp#9]
- [x] Add simple registration **form**
- [x] **Style** form
- [x] Add **validation** for form fields
- [x] Implement **API call** to check if username is taken or email already exists
- [x] Implement **API call** for getting all available questions for password recovery 
- [x] Implement **API call** for sending user data after successful registration
- [x] **Redirect** to login page after successful registration

**Comment by emirpita** [comment]
Successfully implemented.
